Update sxy-ceph-rebuild

diff --git a/sxy-ceph-rebuild b/sxy-ceph-rebuild
--- a/sxy-ceph-rebuild
+++ b/sxy-ceph-rebuild
@@ -1,9 +1,14 @@
 #!/bin/bash -e
 
+export CC=/home/ceph/usr/bin/gcc
+export CXX=/home/ceph/usr/bin/g++
+export PATH=/home/ceph/usr/bin:$PATH
+
 NODENAME=`cat /etc/hostname`
 
 #DIR=/home/ceph/ceph-src/ceph-12.2.5/build
-DIR=/home/ceph/ceph-src/ceph/build
+BASE_DIR=/home/ceph/ceph-src/ceph/
+BUILD_DIR=/home/ceph/ceph-src/ceph/build
 
 function usage() 
 {
@@ -15,6 +20,22 @@ function usage()
 	>&2 echo -e "    -h          Show this help and exit."
 	>&2 echo -e "    -i          Immediate rebuild mode: Build as it is.\n Only \"-r\" option works with this option on."
 	>&2 echo -e "    -r          Restart Ceph components after rebuild."
+}
+
+function maybe_do_cmake()
+{
+	if test ! -d $BUILD_DIR; then
+		export PATH=/usr/cmake-3.14.5/bin/:$PATH
+		./do_cmake.sh
+	fi
+
+	# Still not exist?
+	if test ! -d $BUILD_DIR; then
+		>&2 echo "./do_cmake.sh failed to create directory $BUILD_DIR. Please check."
+		exit 1
+	fi
+	cd $BUILD_DIR
+	rsync /home/ceph/sxy/ceph-build/boost_1_66_0.tar.bz2 boost/src/
 }
 
 g_branch=
@@ -33,12 +54,17 @@ while [ ! -z "$1" ]; do
 	shift
 done
 
-cd $DIR
+if test ! -d $BASE_DIR; then
+	>&2 echo "Project directory $BASE_DIR doesn't exist. Please check."
+	exit 1
+fi
+cd $BASE_DIR
 
 if [ "$g_immediate" == true ]; then
+	maybe_do_cmake
 	set -x
 	make -j32
-	sudo make install -j32
+	sudo env PATH=$PATH make install -j32
 	if [ "$g_restart_flag" == true ]; then
 		sudo systemctl restart ceph.target
 	fi
@@ -55,6 +81,8 @@ bin_ver=${bin_ver#*(}
 bin_ver=${bin_ver%%)*}
 
 git fetch
+
+maybe_do_cmake
 
 cur_branch=
 if [ ! -z "$g_branch" ]; then
@@ -96,7 +124,7 @@ if [ "$latest_commit" != "$bin_ver" ]; then
 		git merge origin/"$cur_branch"
 	fi
 	make -j20
-	sudo make install -j32
+	sudo env PATH=$PATH make install -j32
 fi
 
 if [ "$g_restart_flag" == true ]; then
